##
## EPITECH PROJECT, 2021
## lib
## File description:
## Makefile used to build all the lib contained here
##

############################################################
########################## Flags ###########################
############################################################

# MAKEFLAGS	+=	--no-print-directory -s

SRC	=	   ./my/Makefile \

############################################################
########################## Func ############################
############################################################

.PHONY:	all clean fclean re

all:
	make -C ${SRC}

clean:
	make clean -C ${SRC}

fclean:
	make fclean -C ${SRC}

re:
	make re -C ${SRC}
